### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Tatsuya9156** [Tatsuya9156/protospace-33498#1]
# URL
https://protospace-33498.herokuapp.com/

**Comment by kaho0919** [comment]
ご提出ありがとうございます！

動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！


[修正依頼箇所]
・新規登録後すぐ、「こんにちは、〇〇さん」をクリックし、マイページに遷移しようとすると、「The page you were looking for doesn't exist.」エラーが出ます。(マイページに遷移できるようにしましょう。)
※画像を投稿すると遷移できるようになるので、新規登録後すぐでも遷移できるようにしましょう。



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Tatsuya9156** [comment]
ご確認ありがとうございます！！！
修正しましたぁぁぁ！！！
よろしくお願いします！！！

**Comment by kaho0919** [comment]
ご提出ありがとうございます!

問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
